# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Library/Projects/Subeq/Subleq V2/SubLEQV2Viv/SubLEQV2Viv.cache/wt} [current_project]
set_property parent.project_path {D:/Library/Projects/Subeq/Subleq V2/SubLEQV2Viv/SubLEQV2Viv.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Library/Projects/Subeq/Subleq V2/SubLEQV2Viv/SubLEQV2Viv.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Library/Projects/Subeq/Subleq V2/Sources/CPU.vhd}
  {D:/Library/Projects/Subeq/Subleq V2/Sources/MMU.vhd}
  {D:/Library/Projects/Subeq/Subleq V2/Sources/MainRAM.vhd}
  {D:/Library/Projects/Subeq/Subleq V2/Sources/SFR.vhd}
  {D:/Library/Projects/Subeq/Subleq V2/Sources/cpu_top.vhd}
  {D:/Library/Projects/Subeq/Subleq V2/Sources/board_top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Library/Projects/Subeq/Subleq V2/SubLEQV2Viv/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Library/Projects/Subeq/Subleq V2/SubLEQV2Viv/Nexys4DDR_Master.xdc}}]


synth_design -top board_top -part xc7a100tcsg324-3


write_checkpoint -force -noxdef board_top.dcp

catch { report_utilization -file board_top_utilization_synth.rpt -pb board_top_utilization_synth.pb }
